health_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5433
      user: postgres
      password: postgres
      dbname: health_db
      schema: dbt_dev
      threads: 4
